version: '3.8'

services:
    db:
        image: postgres:13
        environment:
          POSTGRES_DB: sitesdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        volumes:
          - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:6

    web:
        build:
          context: .
          dockerfile: docker/Dockerfile
        command: flask.run --host=0.0.0.0
        volumes:
          - .:/app
        ports:
          - "5000:5000"
        depends_on:
          - db
          - redis
        environment:
          - FlASK_ENV=development

    celery:
        build:
          context: .
          dockerfile: docker/Dockerfile
        command: celery -A app.tasks worker --loglevel=info
        volumes:
          - .:/app
        depends_on:
          - db
          - redis
        environment:
          - FlASK_ENV=development

    celery-beat:
      build:
        context: .
        dockerfile: docker/Dockerfile
      command: celery -A app.tasks beat --loglevel=info
      volumes:
        - .:/app
      depends_on:
        - db
        - redis
      environment:
        - FlASK_ENV=development

volumes:
    postgres_data:
