version: '3.8'

services:
    db:
      image: postgres:13
      environment:
        POSTGRES_DB: sitesdb
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      volumes:
        - .data/postgres:/var/lib/postgresql/data

      
        

    web:
        build:
          context: backend
        entrypoint: ["/code/entrypoint.sh"]
        command: ./manage.py runserver
        #volumes:
        #  - .:/code
        ports:
          - "8989:8000"
        depends_on:
          - db
          

  
