version: '3.8'

services:
    db:
      image: postgres:13
      environment:
        POSTGRES_DB: sitesdb
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      volumes:
        - .data/postgres:/var/lib/postgresql/data
      ports:
        - "5432:5432"

      
        

    web:
        build:
          context: backend
        entrypoint: ["/code/entrypoint.sh"]
        command: python ./manage.py runserver 0.0.0.0:8000
#        volumes:
#          - .:/code
        ports:
          - "8989:8000"
        depends_on:
          - db



#    cron:
#        build: .
#        command: >
#            sh -c "
#            (echo 'SHELL=/bin/sh'; echo '0 0 * * * python ./manage.py openphish' >> /proc/1/fd/1 2>&1') | crontab - && crond -f -l 2"
#        volumes:
#            - .:/code
#        depends_on:
#            - db